# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e3ac07f783c8dc324cad787efeb08ead2937b16359c4fd3ac9677cb5c09d5572ad5c49df0cba0be3b3e404ceedae1d6627cdd5c187dcf69cbfd24fbfa2114b4

test:
  secret_key_base: 1b5b5fcfb6949fc71059aba6e29d8254dc31dc4343aa1eb26f4afd2746746992c715151c6f9960c49dab4e7e4b98a9a60adfc5cc91a84f67559bd836128ccd1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
